version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - ./init-scripts/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"