apiVersion: v1
# 描述单个pod中的一个volume
kind: PersistentVolumeClaim
# pv元数据：名称
metadata:
  # 定义pvc中的volume名称，供deployment中使用
  name: my-local-pvc1
# 具体说明pvc的规格
spec:
  # pvc通过下面三个来和pv匹配：如果有一个不一样，就匹配不上
  storageClassName: suibianaxie
  # 定义pvc需要的资源
  resources:
    requests:
      # 1 GB
      storage: 1Gi
  accessModes:
    # ReadOnlyMany：多个pod可以同时使用，只能读
    # ReadWriteMany：可以被多个pod挂载，随便使用
    # ReadWriteOnce：只能被一个pod挂载、使用
    - ReadWriteOnce
