// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/entity"
	"webook/internal/service"
	"webook/internal/web"
	"webook/internal/web/ijwt"
	"webook/ioc"
	"webook/ioc/oauth2"
	"webook/ioc/sms"
)

// Injectors from wire.go:

// 根目录下运行wire
func InitWebServer() *gin.Engine {
	db := ioc.InitDB()
	userEntity := entity.NewUserEntity(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userEntity, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := sms.InitSmsService()
	codeService := service.NewCodeService(codeRepository, smsService)
	handler := ijwt.NewRedisHandler(cmdable)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	weChatService := oauth2.InitWeChatService()
	oAuth2WeChatHandler := web.NewOAuth2WeChatHandler(weChatService)
	v := ioc.InitMiddlewares(cmdable, handler)
	engine := ioc.InitWebServer(userHandler, oAuth2WeChatHandler, v)
	return engine
}
